### ISSUE TITLE
SQLite and make not installed on Windows 7

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/windows-installer#41]
I'm in a workshop with a machine that has Windows 7 Home Edition Service Pack 1 32-bit machine. The installer installs nano and the rest of tools but neither SQLite nor make.

**Comment by iglpdc** [comment]
Maybe related to #34

**Comment by ethanwhite** [comment]
Can you report the output of `ls ~/.swc` and `cat .bash_profile`?

**Comment by iglpdc** [comment]
![error](https://cloud.githubusercontent.com/assets/1700319/12271393/c405b04e-b928-11e5-8970-99b0ff7769e6.PNG)

We get this error after running the installer. There is no ./swc or .bash_profile in the home dir.

**Comment by iglpdc** [comment]
Ok, so the story is not exactly as I told it. The installer didn't finish running (giving the error above) and nothing was installed (so no `~/.swc` or `.bash_profile` were created.

We fix it by creating these files by hand, downloading the binaries from the website in the installer, and adding `./swc` to the path in the `.bash_profile`

**Comment by wking** [comment]
On Tue, Jan 12, 2016 at 09:52:42AM -0800, Ivan Gonzalez wrote:
> The installer didn't finish running (giving the error above) and
> nothing was installed (so no `~/.swc` or `.bash_profile` were
> created.

That sounds like “the installer crashed before accomplishing anything
at all”.  My guess is that we need a 32-bit build of the Inno Setup
installer.  Until then, folks hitting this on machines with Python
installed should be able to download the Python script and run it from
a terminal.

**Comment by ethanwhite** [comment]
I would think if this was a 32-bit vs. 64-bit issue we'd have run into it by now, but I could be wrong.

My looking around on this suggested it might just be an edge case with a system that has some configuration issue somewhere.

If someone can test on another 32-bit system and confirm one way or the other that would be helpful.

**Comment by MelissaJia** [comment]
I'm having the same problem also working on a 32 bit system but had no problem with 64 utilizing the same software

**Comment by MelissaJia** [comment]
I'm having the same problem also working on a 32 bit system but had no problem with 64 utilizing the same software

**Comment by embray** [comment]
Just to be sure, do we support a 32-bit version of the installer?

**Comment by MelissaJia** [comment]
Possibly but not an easy to use one like swcarpentryinstaller.exe.  However, you can use sqlite via the firefox addon without installing sqlite first.

**Comment by justbennet** [comment]
The installer doesn't seem to add either nano nor make to the GitBash shell's prompt nor to the Windows system path.  Files get installed into ~/.swc/[bin|lib|share] and I can set the path manually and things appear to work.

Should ~/.swc/lib/nano and ~/.swc/lib/make/bin get added to the WIndows PATH, or a .profile or .bash_profile get created in the user's home directory?

**Comment by wking** [comment]
On Tue, Apr 26, 2016 at 01:19:44PM -0700, justbennet wrote:
> Should ~/.swc/lib/nano and ~/.swc/lib/make/bin get added to the
> WIndows PATH, or a .profile or .bash_profile get created in the
> user's home directory?

Yes [1].  If you have ~/.swc but no changes to ~/.bash_profile, I
expect the installer crashed before completing.

[1]: https://github.com/swcarpentry/windows-installer/blob/v0.3/swc-windows-installer.py#L296-L300

**Comment by justbennet** [comment]
Yes, it does seem to crash.  Running from a command window that doesn't close gives me this

C:\Program Files (x86)\swc-installer>swc-windows-installer.exe
Preparing your Software Carpentry awesomeness!
installer version 0.3
create nosetests entrypoint C:\Users\hayden\.swc\bin\nosetests
existing installation at C:\Users\hayden\.swc\lib\make
existing installation at C:\Users\hayden\.swc\lib\make
existing installation at C:\Users\hayden\.swc\lib\nano
existing installation at C:\Users\hayden\.swc\share\nanorc
Traceback (most recent call last):
  File "swc-windows-installer.py", line 326, in <module>
  File "swc-windows-installer.py", line 295, in main
  File "swc-windows-installer.py", line 202, in install_sqlite
  File "swc-windows-installer.py", line 141, in zip_install
  File "swc-windows-installer.py", line 72, in download
  File "urllib2.pyc", line 154, in urlopen
  File "urllib2.pyc", line 431, in open
  File "urllib2.pyc", line 449, in _open
  File "urllib2.pyc", line 409, in _call_chain
  File "urllib2.pyc", line 1240, in https_open
  File "urllib2.pyc", line 1197, in do_open
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate ve
rify failed (_ssl.c:590)>

**Comment by wking** [comment]
On Tue, Apr 26, 2016 at 01:49:09PM -0700, justbennet wrote:
“
   File "swc-windows-installer.py", line 202, in install_sqlite
   File "swc-windows-installer.py", line 141, in zip_install
   File "swc-windows-installer.py", line 72, in download
   …
  urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
”

Is the COMODO CA used by sqlite.org not in your CA list or something?

**Comment by justbennet** [comment]
I had no issues when I manually went to the URL from the source code using Firefox on the same Windows VM.

**Comment by wking** [comment]
On Tue, Apr 26, 2016 at 02:14:47PM -0700, justbennet wrote:
“I had no issues when I manually went to the URL from the source code
using Firefox on the same Windows VM.”

I think Firefox uses its own certificate store, while Python is using
a system certificate store [1].  In a Python 3.4+ shell, can you run:

  $ python3
  Python 3.4.3 (default, Jan 29 2016, 13:29:49)
  [GCC 4.8.4] on linux
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import ssl
  >>> context = ssl.create_default_context()
  >>> context.get_ca_certs()

or similar?  Or you can poke around in the CA and ROOT system stores
referenced by [1].

[1]: https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_default_certs

**Comment by carpenterbennet** [comment]
I will try that tomorrow or the next day.

**Comment by justbennet** [comment]
Yes, Comodo was not present.  After a couple of consultations with Google, I found and installed the certificates to the system store.  This is good to know.

How likely is this issue to crop up?  With @wking's guidance, I got through it, but I would probably not have done the morning of a workshop.

I am only testing this because we are offering people a chance to come get help with installing the software prior to a workshop tomorrow, and I am not a native Windows speaker.

**Comment by wking** [comment]
On Thu, Apr 28, 2016 at 02:17:49PM -0700, justbennet wrote:
> I got through it, but I would probably not have done the morning of
> a workshop.

Fix floated in #48.

**Comment by debpaul** [comment]
I have the same issue trying to install on an old Windows 7 Enterprise. The installer doesn't finish, so I get sqlite not found. This is a win 64-bit machine.
