### ISSUE TITLE
Seems to do nothing in Windows 10; SSL error

### ISSUE THREAD

**Issue by pauljohn32** [swcarpentry/windows-installer#60]
I'm getting ready to help with SC workshop in November, going through your instructions for Windows users. Git Bash works fine, but I can't figure out your installation info for nano. Your software installer puts itself into the program menu.  I can run the program you name there, a terminal pops up very briefly, and closes too quickly to read it. After that is finished, I cannot see any effect.  nano is not available in the Git BASH shell, and I can't find any folder that seems to have "nano.exe" or such. 

I used Git Bash to track along to your install folder and run "swc-windows-installer.exe" interactively. 

$ ./swc-windows-installer.exe
Preparing your Software Carpentry awesomeness!
installer version 0.3
create nosetests entrypoint C:\Users\pauljohn32\.swc\bin\nosetests
existing installation at C:\Users\pauljohn32\.swc\lib\make
existing installation at C:\Users\pauljohn32\.swc\lib\make
Traceback (most recent call last):
  File "swc-windows-installer.py", line 326, in <module>
  File "swc-windows-installer.py", line 293, in main
  File "swc-windows-installer.py", line 173, in install_nano
  File "swc-windows-installer.py", line 141, in zip_install
  File "swc-windows-installer.py", line 72, in download
  File "urllib2.pyc", line 154, in urlopen
  File "urllib2.pyc", line 437, in open
  File "urllib2.pyc", line 550, in http_response
  File "urllib2.pyc", line 469, in error
  File "urllib2.pyc", line 409, in _call_chain
  File "urllib2.pyc", line 656, in http_error_302
  File "urllib2.pyc", line 431, in open
  File "urllib2.pyc", line 449, in _open
  File "urllib2.pyc", line 409, in _call_chain
  File "urllib2.pyc", line 1240, in https_open
  File "urllib2.pyc", line 1197, in do_open
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

I suppose you thought of this, but it is a little weird that your program shows the executable as if it were named "Software Carpentry Windows Installer". That is a bit odd.

**Comment by rgaiacs** [comment]
@pauljohn32 Thanks for the issue. I believe this is a duplicate of #54.
