### ISSUE TITLE
Problems installing on Windows 7

### ISSUE THREAD

**Issue by pschloss** [swcarpentry/windows-installer#61]
I have a workshop that I'm teaching tomorrow and Wednesday and one of the learners is using Windows 7. In a problem that is pretty similar to Issue #42 from last year, we get git-bash, R, and RStudio installed, but not the SWC installer. It creates the `.swc/` folder but not `.bash_profile`. The only thing in `.swc/` is `.swc/bin/nosetests`. When we launch the installer it again flashes up a terminal, seems to do something with nosetest and then I see a bunch of Traceback text before the screen quickly closes. FWIW, it is a 64 bit OS and we do seem to be in the home directory. We've also uninstalled, downloaded, and installed several times now. Ideas?

**Comment by wking** [comment]
On Mon, Jan 16, 2017 at 09:10:09AM -0800, Pat Schloss wrote:
> … I see a bunch of Traceback text before the screen quickly closes.

Try running the installation script [1] from the command line.  Then
you'll have time to read the tracebacks (and paste them in here :).

[1]: https://github.com/swcarpentry/windows-installer/blob/v0.3/swc-windows-installer.py

**Comment by pschloss** [comment]
$ AppData/Local/Programs/Python/Python36-32/python.exe Desktop/swc-windows-installer.py
Preparing your Software Carpentry awesomeness!
installer version 0.3
create nosetests entrypoint C:\Users\Holoshitz lab\.swc\bin\nosetests
Traceback (most recent call last):
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Desktop/swc-windows-installer.py", line 326, in <module>
    main()
  File "Desktop/swc-windows-installer.py", line 292, in main
    install_make(install_directory=make_dir)
  File "Desktop/swc-windows-installer.py", line 160, in install_make
    path=os.path.join(install_directory, 'bin', 'make.exe'))
  File "Desktop/swc-windows-installer.py", line 141, in zip_install
    zip_bytes = download(url=url, sha1=sha1)
  File "Desktop/swc-windows-installer.py", line 72, in download
    r = _urlopen(url)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>

**Comment by wking** [comment]
On Mon, Jan 16, 2017 at 09:28:05AM -0800, Pat Schloss wrote:
>   File "Desktop/swc-windows-installer.py", line 292, in main
>     install_make(install_directory=make_dir)
>   File "Desktop/swc-windows-installer.py", line 160, in install_make
>     path=os.path.join(install_directory, 'bin', 'make.exe'))
>   File "Desktop/swc-windows-installer.py", line 141, in zip_install
>     zip_bytes = download(url=url, sha1=sha1)
>   File "Desktop/swc-windows-installer.py", line 72, in download
>     r = _urlopen(url)
>   …
>   File "C:\Users\Holoshitz lab\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 1320, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>

This looks like #54 and #60, which we still don't have a fix for.  You
can work around it by installing the broken package by hand
(e.g. download [1,2] and unpack them into ~\.swc\opt\make).  Or by
hosting the sources somewhere that can be reached without TLS and
replacing the installation script's current URLs with your alternate
location.

[1]: http://downloads.sourceforge.net/project/gnuwin32/make/3.81/make-3.81-bin.zip
[2]: http://downloads.sourceforge.net/project/gnuwin32/make/3.81/make-3.81-dep.zip

**Comment by pschloss** [comment]
Ok, thanks - is this something we should expect to be a problem for all windows users or is it a fluke?

**Comment by embray** [comment]
It will probably be a problem for many Windows users.  Right now, honestly, I wouldn't put too much stock in the existing Windows installer at all, and not just for that reason.

I have a plan for redoing it but there's been slow to grow consensus on what to do.  Sorry.
