### ISSUE TITLE
Cannot run nano in Git CMD

### ISSUE THREAD

**Issue by CHK16** [swcarpentry/windows-installer#63]
Hi, 

I tried to run nano in Git CMD and it shows 
$ nano
bash: nano: command not found

Then I tried to run the swc-windows-installer and it shows

chkuo@DESKTOP-NDJFFKL MINGW64 ~
$ swc-windows-installer
Preparing your Software Carpentry awesomeness!
installer version 0.3
create nosetests entrypoint C:\Users\chkuo\.swc\bin\nosetests
existing installation at C:\Users\chkuo\.swc\lib\make
existing installation at C:\Users\chkuo\.swc\lib\make
Traceback (most recent call last):
  File "swc-windows-installer.py", line 326, in <module>
  File "swc-windows-installer.py", line 293, in main
  File "swc-windows-installer.py", line 173, in install_nano
  File "swc-windows-installer.py", line 141, in zip_install
  File "swc-windows-installer.py", line 72, in download
  File "urllib2.pyc", line 154, in urlopen
  File "urllib2.pyc", line 437, in open
  File "urllib2.pyc", line 550, in http_response
  File "urllib2.pyc", line 469, in error
  File "urllib2.pyc", line 409, in _call_chain
  File "urllib2.pyc", line 656, in http_error_302
  File "urllib2.pyc", line 431, in open
  File "urllib2.pyc", line 449, in _open
  File "urllib2.pyc", line 409, in _call_chain
  File "urllib2.pyc", line 1240, in https_open
  File "urllib2.pyc", line 1197, in do_open
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

chkuo@DESKTOP-NDJFFKL MINGW64 ~

Does anyone know how to solve this issue?

Thanks

**Comment by rgaiacs** [comment]
@CHK16 Thanks for your report.

The error that you encounter when running the installer is due a certification verification. The only way that you can solve/workaround that error is to add the certification of the website the installer is trying to access to the list of valid certificates on your machine. I don't remember how you can do that. :-(

**Comment by CHK16** [comment]
Thank you for the response. I reinstall it and it's working now.

**Comment by alex-konovalov** [comment]
@CHK16 @rgaiacs me and @pgmccann are dealing with a Win7 machine with exactly the same issue now. Any further tips?

**Comment by rgaiacs** [comment]
@alex-konovalov Sorry for the delay. :-( Your original message got queue when I was travelling.

> are dealing with a Win7 machine with exactly the same issue now. Any further tips?

I don't.
